%YAML 1.1
---
zero-gpu-utilization-della-gpu:
  first_warning_minutes: 60
  second_warning_minutes: 105
  cancel_minutes: 120
  sampling_period_minutes: 15
  min_previous_warnings: 1
  clusters:
    - della
  partition:
    - gpu
  excluded_users:
    - aturing
    - einstein

############################
## LOW CPU/GPU EFFICIENCY ##
############################
low-xpu-efficiency-della-cpu:
  cluster: della
  cluster_name: "Della (cpu)"
  partitions:
  - cpu
  xpu: cpu


#######################
## EXCESS CPU MEMORY ##
#######################
excess-cpu-memory-della-cpu:
  tb_hours_per_day: 10
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  clusters:
    - della
  partition:
    - cpu
  combine_partitions: False
  cores_per_node: 28
  excluded_users:
    - aturing
    - einstein
    - vonholdt

excess-cpu-memory-della-datascience:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 10
  clusters:
    - della
  partition:
    - datasci
  combine_partitions: False
  cores_per_node: 10000
  excluded_users:
    - aturing
    - einstein


excess-cpu-memory-stellar:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  clusters:
    - stellar
  partition:
    - all
    - pppl
    - pu
    - serial
  combine_partitions: False
  cores_per_node: 76.8
  excluded_users:
    - aturing
    - einstein


excess-cpu-memory-tiger:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  clusters:
    - tiger
  partition:
    - cpu
    - ext
    - serial
  combine_partitions: True
  cores_per_node: 32
  excluded_users:
    - aturing
    - einstein
