%YAML 1.1
---
low-gpu-utilization-mc:
  low_gpu_util: 1
  first_warning_minutes: 60
  cancel_minutes: 120
  max_interactive_hours: 6
  clusters:
    - mc
  partitions:
    - mc
  excluded_users:
    - ubuntu
  admin_emails:
    - amandio.faustino@kaust.edu.sa
