%YAML 1.1
---
excess-cpu-memory-della-cpu:
  tb_hours_per_day: 10
  ratio_threshold: 0.35
  mean_ratio_threshold: 0.35
  median_ratio_threshold: 0.35
  num_top_users: 10
  clusters:
    - della
  partition:
    - cpu
  combine_partitions: False
  cores_per_node: 28
  excluded_users:
    - aturing
    - einstein


excess-cpu-memory-della-datascience:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 10
  clusters:
    - della
  partition:
    - datasci
  combine_partitions: False
  cores_per_node: 10000
  excluded_users:
    - aturing
    - einstein


excess-cpu-memory-stellar:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  clusters:
    - stellar
  partition:
    - all
    - pppl
    - pu
    - serial
  combine_partitions: False
  cores_per_node: 76.8
  excluded_users:
    - aturing
    - einstein


excess-cpu-memory-tiger:
  tb_hours_per_day: 10000
  ratio_threshold: 0.25
  mean_ratio_threshold: 0.25
  median_ratio_threshold: 0.25
  num_top_users: 5
  clusters:
    - tiger
  partition:
    - cpu
    - ext
    - serial
  combine_partitions: True
  cores_per_node: 32
  excluded_users:
    - aturing
    - einstein
