name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: Check Python 3.6 on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - name: Install package
        run: python -m pip install -e .[test]

      - name: Test package
        run: python -m pytest
